// Real Estate Website — Property Data
// Managed client-side as JSON objects per project scope (no backend/database required for demo)

const PROPERTIES = [
  {
    id: "P001",
    type: "2BHK",
    project: "Hiranandani Meadows",
    area: 650,
    price: 6500000,
    priceLabel: "₹65 Lakh",
    location: "Powai, Mumbai",
    locality: "Powai",
    city: "Mumbai",
    amenities: ["Gymnasium", "24x7 Security", "Children's Play Area", "Power Backup"],
    connectivity: "8 min to Powai Lake, 15 min to Powai Business Park, close to JVLR",
    rera: "RERA Registered · P51800012345",
    status: "OC Received",
    facade: "deco-1",
    floor: "7th of 14",
    facing: "East",
    possession: "Ready to Move"
  },
  {
    id: "P002",
    type: "3BHK",
    project: "Lodha Eternis",
    area: 950,
    price: 11000000,
    priceLabel: "₹1.1 Cr",
    location: "Andheri, Mumbai",
    locality: "Andheri East",
    city: "Mumbai",
    amenities: ["Clubhouse", "Swimming Pool", "Landscaped Garden", "Covered Parking"],
    connectivity: "5 min to Andheri Station, 10 min to Western Express Highway",
    rera: "RERA Registered · P51800023456",
    status: "CC Received",
    facade: "deco-2",
    floor: "12th of 22",
    facing: "West",
    possession: "Dec 2026"
  },
  {
    id: "P003",
    type: "2BHK",
    project: "Runwal Gardens",
    area: 620,
    price: 5800000,
    priceLabel: "₹58 Lakh",
    location: "Thane West, Mumbai",
    locality: "Thane West",
    city: "Mumbai",
    amenities: ["Jogging Track", "Amphitheatre", "24x7 Security", "Indoor Games Room"],
    connectivity: "Close to Ghodbunder Road, 12 min to Viviana Mall",
    rera: "RERA Registered · P51700034567",
    status: "Under Construction",
    facade: "deco-1",
    floor: "4th of 18",
    facing: "North",
    possession: "Jun 2027"
  },
  {
    id: "P004",
    type: "3BHK",
    project: "Oberoi Sky City",
    area: 1020,
    price: 18500000,
    priceLabel: "₹1.85 Cr",
    location: "Borivali East, Mumbai",
    locality: "Borivali East",
    city: "Mumbai",
    amenities: ["Sky Lounge", "Infinity Pool", "Spa", "Valet Parking"],
    connectivity: "3 min to Borivali Station, 10 min to Western Express Highway",
    rera: "RERA Registered · P51800045678",
    status: "OC Received",
    facade: "deco-2",
    floor: "18th of 30",
    facing: "South-West",
    possession: "Ready to Move"
  },
  {
    id: "P005",
    type: "2BHK",
    project: "Godrej Emerald",
    area: 680,
    price: 8900000,
    priceLabel: "₹89 Lakh",
    location: "Mulund West, Mumbai",
    locality: "Mulund West",
    city: "Mumbai",
    amenities: ["Rooftop Garden", "Gymnasium", "24x7 Security", "EV Charging"],
    connectivity: "6 min to Mulund Station, near LBS Marg",
    rera: "RERA Registered · P51800056789",
    status: "CC Received",
    facade: "deco-1",
    floor: "9th of 16",
    facing: "East",
    possession: "Mar 2027"
  },
  {
    id: "P006",
    type: "3BHK",
    project: "Kalpataru Vivant",
    area: 980,
    price: 15200000,
    priceLabel: "₹1.52 Cr",
    location: "Thane, Mumbai",
    locality: "Thane",
    city: "Mumbai",
    amenities: ["Clubhouse", "Tennis Court", "Landscaped Garden", "Power Backup"],
    connectivity: "10 min to Thane Station, close to Eastern Express Highway",
    rera: "RERA Registered · P51700067890",
    status: "Under Construction",
    facade: "deco-2",
    floor: "6th of 20",
    facing: "North-East",
    possession: "Sep 2026"
  }
];

// Helper: format INR without external libraries
function formatINR(amount) {
  return "₹" + amount.toLocaleString("en-IN");
}
